spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: 19801980
  url: jdbc:postgresql://localhost:5432/warehouse?currentSchema=main
 flyway:
  locations: "classpath:db/migration"
  validate-on-migrate: false
  encoding: UTF-8
  out-of-order: true
 servlet:
  multipart:
   max-file-size: 10MB
springdoc:
 swagger-ui:
  path: /sw
 api-docs:
  path: /api-docs
server:
 port: 9090

api:
 info:
  version: 0.0.1
  title: API for warehouses managment
  description: bla, bla ..
url:
 info:
  host: localhost
  protocol: http
